import {
  Activity,
  Atom,
  Braces,
  Camera,
  Cloud,
  Code,
  Coffee,
  Container,
  Database,
  FlaskConical,
  Flame,
  Github,
  Grid3x3,
  HardDrive,
  Hexagon,
  Layers,
  Leaf,
  ListChecks,
  MessageSquare,
  Route,
  ScanEye,
  Search,
  Sigma,
  Sparkles,
  Table,
  Terminal,
  Wind,
  Zap,
  GitBranch,
  type LucideIcon,
} from "lucide-react";

const map: Record<string, LucideIcon> = {
  activity: Activity,
  atom: Atom,
  braces: Braces,
  camera: Camera,
  cloud: Cloud,
  code: Code,
  coffee: Coffee,
  container: Container,
  database: Database,
  flaskconical: FlaskConical,
  flame: Flame,
  github: Github,
  gitbranch: GitBranch,
  grid: Grid3x3,
  hardDrive: HardDrive,
  hexagon: Hexagon,
  layers: Layers,
  leaf: Leaf,
  listchecks: ListChecks,
  messagesquare: MessageSquare,
  route: Route,
  scaneye: ScanEye,
  search: Search,
  sigma: Sigma,
  sparkles: Sparkles,
  table: Table,
  terminal: Terminal,
  wind: Wind,
  zap: Zap,
};

/** Resolves a data-driven icon key to a lucide icon. */
export function TechIcon({ name, className = "" }: { name: string; className?: string }) {
  const Icon = map[name] ?? Code;
  return <Icon className={className} aria-hidden />;
}
