"""Generate responsive .webp variants next to each raster image in public/images."""
import os
from PIL import Image

WIDTHS = [480, 768, 1200, 1600]
ROOT = "public/images"

for r, _, files in os.walk(ROOT):
    for n in files:
        if not n.lower().endswith((".jpg", ".jpeg", ".png")) or "-w" in n:
            continue
        p = os.path.join(r, n)
        im = Image.open(p).convert("RGB")
        base = os.path.splitext(p)[0]
        for w in WIDTHS:
            if w > im.width:
                continue
            out = f"{base}-w{w}.webp"
            im.resize((w, round(im.height * w / im.width)), Image.LANCZOS).save(out, "WEBP", quality=78, method=6)
            print(out, round(os.path.getsize(out) / 1024), "KB")
        full = f"{base}-w{im.width}.webp"
        if im.width not in WIDTHS:
            im.save(full, "WEBP", quality=78, method=6)
            print(full, round(os.path.getsize(full) / 1024), "KB")

# --- emit manifest consumed by <SmartImage> / <ImageWithFallback> ---
manifest = {}
for r, _, files in os.walk(ROOT):
    for n in files:
        if not n.endswith(".webp") or "-w" not in n:
            continue
        base, w = n.rsplit("-w", 1)
        w = int(w[:-5])
        ext = None
        for cand in (".jpg", ".jpeg", ".png"):
            if os.path.exists(os.path.join(r, base + cand)):
                ext = cand
        if not ext:
            continue
        key = "/" + os.path.join(r, base + ext).split("public/", 1)[1]
        manifest.setdefault(key, []).append(w)

lines = [
    "// AUTO-GENERATED by scripts/gen-image-variants.py — do not edit by hand.",
    "export const imageVariants: Record<string, number[]> = {",
]
for k in sorted(manifest):
    lines.append(f'  "{k}": [{", ".join(str(w) for w in sorted(set(manifest[k])))}],')
lines += ["};", ""]
open("src/lib/image-variants.generated.ts", "w").write("\n".join(lines))
print("manifest entries:", len(manifest))
